name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  linux:
    uses: externpro/externpro/.github/workflows/build-linux.yml@main
    with:
      email: anderson.scott.m@icloud.com
      runon: ubuntu-latest

  linux-arm64:
    uses: externpro/externpro/.github/workflows/build-linux.yml@main
    with:
      email: anderson.scott.m@icloud.com
      runon: ubuntu-24.04-arm

  windows:
    uses: externpro/externpro/.github/workflows/build-windows.yml@main
